
export const PRODUCT_MAP = {
  1: "Essence Mascara Lash Princess",
  2: "Eyeshadow Palette with Mirror",
  3: "Powder Canister",
  4: "Red Lipstick",
  5: "Red Nail Polish",
  6: "Calvin Klein CK One",
  7: "Chanel Coco Noir Eau De",
  8: "Dior J'adore",
  9: "Dolce Shine Eau de",
  10: "Gucci Bloom Eau de",
  11: "Annibale Colombo Bed",
  12: "Annibale Colombo Sofa",
  13: "Bedside Table African Cherry",
  14: "Knoll Saarinen Executive Conference Chair",
  15: "Wooden Bathroom Sink With Mirror",
  16: "Apple",
  17: "Beef Steak",
  18: "Cat Food",
  19: "Chicken Meat",
  20: "Cooking Oil",
  21: "Cucumber",
  22: "Dog Food",
  23: "Eggs",
  24: "Fish Steak",
  25: "Green Bell Pepper",
  26: "Green Chili Pepper",
  27: "Honey Jar",
  28: "Ice Cream",
  29: "Juice",
  30: "Kiwi",

  31: "Lemon",
  32: "Milk",
  33: "Mulberry",
  34: "Nescafe Coffee",
  35: "Potatoes",
  36: "Protein Powder",
  37: "Red Onions",
  38: "Rice",
  39: "Soft Drinks",
  40: "Strawberry",
  41: "Tissue Paper Box",
  42: "Water",
  43: "Decoration Swing",
  44: "Family Tree Photo Frame",
  45: "House Showpiece Plant",
  46: "Plant Pot",
  47: "Table Lamp",
  48: "Bamboo Spatula",
  49: "Black Aluminium Cup",
  50: "Black Whisk",
  51: "Boxed Blender",
  52: "Carbon Steel Wok",
  53: "Chopping Board",
  54: "Citrus Squeezer Yellow",
  55: "Egg Slicer",
  56: "Electric Stove",
  57: "Fine Mesh Strainer",
  58: "Fork",
  59: "Glass",
  60: "Grater Black",

  61: "Hand Blender",
  62: "Ice Cube Tray",
  63: "Kitchen Sieve",
  64: "Knife",
  65: "Lunch Box",
  66: "Microwave Oven",
  67: "Mug Tree Stand",
  68: "Pan",
  69: "Plate",
  70: "Red Tongs",
  71: "Silver Pot With Glass Cap",
  72: "Slotted Turner",
  73: "Spice Rack",
  74: "Spoon",
  75: "Tray",
  76: "Wooden Rolling Pin",
  77: "Yellow Peeler",
  78: "Apple MacBook Pro 14 Inch Space Grey",
  79: "Asus Zenbook Pro Dual Screen Laptop",
  80: "Huawei Matebook X Pro",
  81: "Lenovo Yoga 920",
  82: "New DELL XPS 13 9300 Laptop",
  83: "Blue & Black Check Shirt",
  84: "Gigabyte Aorus Men Tshirt",
  85: "Man Plaid Shirt",
  86: "Man Short Sleeve Shirt",
  87: "Men Check Shirt",
  88: "Nike Air Jordan 1 Red And Black",
  89: "Nike Baseball Cleats",
  90: "Puma Future Rider Trainers",
};
